
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author byron_rigdkvz
 */
public class jAnoBiciesto extends javax.swing.JFrame {

    /**
     * Creates new form jAnoBiciesto
     */
    public jAnoBiciesto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTitulo = new javax.swing.JLabel();
        SubTitulo = new javax.swing.JLabel();
        jText = new javax.swing.JTextField();
        jLimpiar = new javax.swing.JButton();
        jSalir = new javax.swing.JButton();
        jValidar2 = new javax.swing.JButton();
        jFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTitulo.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jTitulo.setText("Quieres saber que año es bisiesto?");
        getContentPane().add(jTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        SubTitulo.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        SubTitulo.setForeground(new java.awt.Color(0, 0, 204));
        SubTitulo.setText("Favor ingresar un año:");
        getContentPane().add(SubTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jText, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 130, 50));

        jLimpiar.setBackground(new java.awt.Color(153, 153, 153));
        jLimpiar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLimpiar.setText("LIMPIAR");
        jLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 120, 40));

        jSalir.setBackground(new java.awt.Color(153, 153, 153));
        jSalir.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jSalir.setText("SALIR");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 120, 40));

        jValidar2.setBackground(new java.awt.Color(153, 153, 153));
        jValidar2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jValidar2.setText("VALIDAR");
        jValidar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValidar2ActionPerformed(evt);
            }
        });
        getContentPane().add(jValidar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 120, 40));

        jFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/wallpaper1.jpg"))); // NOI18N
        getContentPane().add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jSalirActionPerformed

    private void jLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimpiarActionPerformed
        jText.setText("");
    }//GEN-LAST:event_jLimpiarActionPerformed

    private void jValidar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValidar2ActionPerformed
        int A;
        A=Integer.parseInt(jText.getText());
        if (A % 4 == 0 &&(A%100 !=0)||(A % 400 ==0))
            if (A == 0)
                JOptionPane.showMessageDialog(null,"No puedes digitar 0");
            else
                JOptionPane.showMessageDialog(null,"El año es bisiesto");
        else
            JOptionPane.showMessageDialog(null,"El año no es bisiesto");
    }//GEN-LAST:event_jValidar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jAnoBiciesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jAnoBiciesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jAnoBiciesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jAnoBiciesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jAnoBiciesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SubTitulo;
    private javax.swing.JLabel jFondo;
    private javax.swing.JButton jLimpiar;
    private javax.swing.JButton jSalir;
    private javax.swing.JTextField jText;
    private javax.swing.JLabel jTitulo;
    private javax.swing.JButton jValidar2;
    // End of variables declaration//GEN-END:variables
}
